name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Package XCFramework
      run: |
        ./make-package.command
      env:
        # Seems unable build visionOS at the moment
        B9_BUILD_VISION_OS: false
